# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            # Routes starting with /api will primarily respond with JSON, but they also allow HTML as an option.
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            # Routes that don't start with /api will primarily respond with HTML but will accept any format as a fallback.
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
