controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

#umami_recipes:
#    path: '/umami/recipes'
#    controller: 'App\Controller\UmamiRecipesController::index'
